name: Backend Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.8.0

      - name: Install dependencies
        run: npm install 
        working-directory: backend-api
        id: install-dependencies

      - name: Install PM2 globally
        run: npm install pm2@latest -g

      - name: Show PM2 version
        run: pm2 -V

      - name: Show PM2 process list
        run: pm2 list

      - name: Start app with PM2
        run: pm2 start ecosystem.config.js --env=production
        working-directory: backend-api

      - name:   Restart app with PM2
        run: pm2 restart ecosystem.config.js --env=production 
        working-directory: backend-api
