name: Backend Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
        working-directory: backend-api
        id: install-dependencies

      - name: Run build
        run: npm run build
        working-directory: backend-api
        id: run-build

      - name: Install PM2 globally
        run: npm install pm2@latest -g

      - name: Show PM2 version
        run: pm2 -V

      - name: Show PM2 process list
        run: pm2 list

      - name: Start app with PM2
        run: pm2 start ecosystem.js --env=production
        working-directory: backend-api
